#!/usr/bin/env bash
# Will indefinitely write "I am alive" to the file /tmp/my_process.
#  Then pauses two seconds in between each message.

while true
do
  echo "I am alive!" >> /tmp/my_process
  sleep 2
done
